version: '3.8'

services:
  web:
    build: ./
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "54322:5432"  # Mapeia a porta 5432 do contêiner para a porta 54322 da máquina host
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
